version: '3.9'

services:
  apiservice1:
    image: apiservice:1.1
    build:
      context: ./Lab1
    container_name: api-service-1
    environment:
      - HOSTNAME=mysqldb
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysqldb
    ports:
      - '8081:8080'
    networks:
      - 'lab2net'
  apiservice2:
    image: apiservice:1.1
    build:
      context: ./Lab1
    container_name: api-service-2
    environment:
      - HOSTNAME=mysqldb
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysqldb
    ports:
      - '8082:8080'
    networks:
      - 'lab2net'
  nginxservice:
    image: nginx:latest
    depends_on:
      - apiservice1
      - apiservice2
    ports:
      - '8080:8080'
    volumes:
      - ./nginxservice/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - 'lab2net'
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Lab1
    ports:
      - '3306:3306'
    networks:
      - 'lab2net'

networks:
  lab2net:
    name: lab2net