version: '3.9'

services:
  apiservice1:
    image: apiservice:1.1
    build:
      context: ./Lab1
    container_name: apiservice1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/Lab1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVICENAME: API-1
      RABBIT_HOST: rabbitmq
    depends_on:
      - mysqldb
    ports:
      - '8081:8080'
    networks:
      - 'lab2net'
  apiservice2:
    image: apiservice:1.1
    build:
      context: ./Lab1
    container_name: apiservice2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/Lab1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVICENAME: API-2
      RABBIT_HOST: rabbitmq
    depends_on:
      - mysqldb
    ports:
      - '8082:8080'
    networks:
      - 'lab2net'
  nginxservice:
    image: nginx:latest
    container_name: nginxservice
    depends_on:
      - apiservice1
      - apiservice2
    ports:
      - '8080:80'
    volumes:
      - ./nginxservice/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - 'lab2net'
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Lab1
    ports:
      - '3306:3306'
    networks:
      - 'lab2net'
  emailservice:
    image: emailservice:1
    container_name: email_service
    build:
      context: ./EmailService
    ports:
      - '8083:8080'
    environment:
      RABBIT_HOST: rabbitmq
    depends_on:
      - apiservice1
      - apiservice2
      - rabbitmq
    networks:
      - 'lab2net'
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - 'lab2net'

networks:
  lab2net:
    name: lab2net